### ISSUE TITLE
 Inquiry About Training Code for QuadricsNet

### ISSUE THREAD

**Issue by wanghanxiao123** [MichaelWu99-lab/QuadricsNet#1]
Dear Michael,

Hello! I've been exploring your project, QuadricsNet, and I am very impressed by your work. I am trying to understand and replicate your findings, but I noticed that the training code seems to be missing in the current code repository. Are there any plans to release the training code publicly? It would be greatly beneficial for my research endeavors.

Thank you very much for your contributions to the project and the open-source community at large. I look forward to your response.

Best regards,
Hanxiao

**Comment by MichaelWu99-lab** [comment]
Thank you for your attention, we plan to release the full code once the paper has been accepted.

**Comment by wanghanxiao123** [comment]
Thank you for your previous response. I have encountered some difficulties in reproducing the results presented in your paper. I noticed that the 'res' values obtained during the demonstration are significantly higher than the 0.01 mentioned in your study. I have been using the default parameter DOWN_SAMPLE_NUM = 40000. Here are some of the sample results I obtained:

Sample 0: seg_iou: 1.0, type_iou: 1.0, res: 0.01413
Sample 1: seg_iou: 1.0, type_iou: 1.0, res: 0.04542
Sample 2: seg_iou: 1.0, type_iou: 1.0, res: 0.02326
Sample 3: seg_iou: 0.9685, type_iou: 1.0, res: 0.0538
Sample 4: seg_iou: 0.9915, type_iou: 1.0, res: 0.02342
Sample 5: seg_iou: 1.0, type_iou: 1.0, res: 0.02606
Sample 6: seg_iou: 0.9503, type_iou: 1.0, res: 0.02675
It is almost the same when testing on the dataset, Could you please advise on what steps I should take or parameters I might adjust to accurately replicate the results in your paper? Are there any additional suggestions or details that I might have overlooked?

I look forward to your guidance to better understand and apply the findings of your research.

**Comment by MichaelWu99-lab** [comment]
When generating reconstruction results, you can adjust the parameters in test_e2e_vis.py at lines 237 'resolution' and 254-270 to generate more accurate results, although it may result in higher memory overhead.
The new configuration has been updated.
